name: 'Build snapshot'
description: 'Build a QL snapshot'
inputs:
  odasa:
    description: 'URL of odasa.zip'
    required: true
  license:
    description: 'URL of license.dat'
    required: true
  language:
    description: 'Language to analyze'
    required: true
outputs:
  snapshot:
    description: 'The snapshot folder'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.odasa }}
    - ${{ inputs.license }}
    - ${{ inputs.language }}
